image: node:latest

stages:
  - Test
  - Build

cache:
  paths:
  - node_modules/

Test:
  stage: Test
  script:
  - npm install --quiet
  - npm test

Build:
  stage: Build
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD registry.uwm-nm-te-capstone.com
    - docker build -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_NAME:$CI_COMMIT_SHA -t registry.uwm-nm-te-capstone.com:8083/CI_PROJECT_NAME:latest .
    - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push registry.uwm-nm-te-capstone.com:8083/CI_PROJECT_NAME:latest
#  only:
#    - master
  when: on_success