stages:
  - Test
  - Build

Test:
  stage: Test
  image: node:latest
  artifacts:
      paths:
      - ./coverage/lcov.info
      expire_in: 1d
  script:
  - npm install --quiet
  - npm test

Build:
  stage: build
  image: node:latest
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD registry.uwm-nm-te-capstone.com
    - docker build -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_NAME:$CI_COMMIT_SHA -t registry.uwm-nm-te-capstone.com:8083/CI_PROJECT_NAME:latest .
    - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_NAME:$CI_COMMIT_SHA
    - docker push registry.uwm-nm-te-capstone.com:8083/CI_PROJECT_NAME:latest
#  only:
#    - master
  when: on_success